CREATE TABLE indices_estruturais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL UNIQUE REFERENCES snapshots(id) ON DELETE CASCADE,
  parcial BOOLEAN NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT indices_estruturais_snapshot_id_id_unico UNIQUE (snapshot_id, id)
);

CREATE TABLE arquivos_indice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indice_id BIGINT NOT NULL,
  snapshot_id BIGINT NOT NULL,
  id_fato TEXT NOT NULL,
  caminho TEXT NOT NULL,
  tipo TEXT NOT NULL,
  blob_sha TEXT NOT NULL CHECK (blob_sha ~ '^[0-9a-fA-F]{40}$'),
  CONSTRAINT arquivos_indice_id_fato_unico UNIQUE (snapshot_id, id_fato),
  CONSTRAINT arquivos_indice_caminho_unico UNIQUE (snapshot_id, caminho),
  CONSTRAINT arquivos_indice_snapshot_id_id_unico UNIQUE (snapshot_id, id),
  CONSTRAINT arquivos_indice_tipo_valido CHECK (tipo IN ('javascript', 'typescript')),
  CONSTRAINT arquivos_indice_indice_fk
    FOREIGN KEY (snapshot_id, indice_id)
    REFERENCES indices_estruturais(snapshot_id, id)
    ON DELETE CASCADE
);

CREATE TABLE simbolos_indice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL,
  id_fato TEXT NOT NULL,
  arquivo_id TEXT NOT NULL,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL,
  evidencia_caminho TEXT NOT NULL,
  evidencia_inicio_linha INTEGER NOT NULL CHECK (evidencia_inicio_linha > 0),
  evidencia_inicio_coluna INTEGER NOT NULL CHECK (evidencia_inicio_coluna > 0),
  evidencia_fim_linha INTEGER NOT NULL CHECK (evidencia_fim_linha > 0),
  evidencia_fim_coluna INTEGER NOT NULL CHECK (evidencia_fim_coluna > 0),
  CONSTRAINT simbolos_indice_evidencia_ordenada CHECK (
    evidencia_fim_linha > evidencia_inicio_linha
    OR (
      evidencia_fim_linha = evidencia_inicio_linha
      AND evidencia_fim_coluna >= evidencia_inicio_coluna
    )
  ),
  CONSTRAINT simbolos_indice_id_fato_unico UNIQUE (snapshot_id, id_fato),
  CONSTRAINT simbolos_indice_tipo_valido CHECK (
    tipo IN ('funcao', 'classe', 'constante', 'componente', 'interface', 'tipo')
  ),
  CONSTRAINT simbolos_indice_arquivo_fk
    FOREIGN KEY (snapshot_id, arquivo_id)
    REFERENCES arquivos_indice(snapshot_id, id_fato)
    ON DELETE CASCADE,
  CONSTRAINT simbolos_indice_evidencia_fk
    FOREIGN KEY (snapshot_id, evidencia_caminho)
    REFERENCES arquivos_indice(snapshot_id, caminho)
    ON DELETE CASCADE
);

CREATE TABLE exportacoes_indice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL,
  id_fato TEXT NOT NULL,
  arquivo_origem_id TEXT NOT NULL,
  nome_exportado TEXT NOT NULL,
  tipo TEXT NOT NULL,
  nome_local TEXT,
  destino_tipo TEXT,
  destino_caminho TEXT,
  destino_especificador TEXT,
  destino_expressao TEXT,
  evidencia_caminho TEXT NOT NULL,
  evidencia_inicio_linha INTEGER NOT NULL CHECK (evidencia_inicio_linha > 0),
  evidencia_inicio_coluna INTEGER NOT NULL CHECK (evidencia_inicio_coluna > 0),
  evidencia_fim_linha INTEGER NOT NULL CHECK (evidencia_fim_linha > 0),
  evidencia_fim_coluna INTEGER NOT NULL CHECK (evidencia_fim_coluna > 0),
  CONSTRAINT exportacoes_indice_evidencia_ordenada CHECK (
    evidencia_fim_linha > evidencia_inicio_linha
    OR (
      evidencia_fim_linha = evidencia_inicio_linha
      AND evidencia_fim_coluna >= evidencia_inicio_coluna
    )
  ),
  CONSTRAINT exportacoes_indice_id_fato_unico UNIQUE (snapshot_id, id_fato),
  CONSTRAINT exportacoes_indice_tipo_valido CHECK (
    tipo IN ('nomeada', 'padrao', 'reexportacao')
  ),
  CONSTRAINT exportacoes_indice_destino_valido CHECK (
    (
      destino_tipo IS NULL
      AND destino_caminho IS NULL
      AND destino_especificador IS NULL
      AND destino_expressao IS NULL
    )
    OR (
      destino_tipo = 'interno'
      AND destino_caminho IS NOT NULL
      AND destino_especificador IS NULL
      AND destino_expressao IS NULL
    )
    OR (
      destino_tipo = 'externo'
      AND destino_caminho IS NULL
      AND destino_especificador IS NOT NULL
      AND destino_expressao IS NULL
    )
    OR (
      destino_tipo = 'nao-resolvido'
      AND destino_caminho IS NULL
      AND destino_especificador IS NOT NULL
    )
  ),
  CONSTRAINT exportacoes_indice_arquivo_fk
    FOREIGN KEY (snapshot_id, arquivo_origem_id)
    REFERENCES arquivos_indice(snapshot_id, id_fato)
    ON DELETE CASCADE,
  CONSTRAINT exportacoes_indice_destino_interno_fk
    FOREIGN KEY (snapshot_id, destino_caminho)
    REFERENCES arquivos_indice(snapshot_id, caminho)
    ON DELETE CASCADE,
  CONSTRAINT exportacoes_indice_evidencia_fk
    FOREIGN KEY (snapshot_id, evidencia_caminho)
    REFERENCES arquivos_indice(snapshot_id, caminho)
    ON DELETE CASCADE
);

CREATE TABLE relacoes_importacao_indice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL,
  id_fato TEXT NOT NULL,
  tipo TEXT NOT NULL,
  arquivo_origem_id TEXT NOT NULL,
  destino_tipo TEXT NOT NULL,
  destino_caminho TEXT,
  destino_especificador TEXT,
  destino_expressao TEXT,
  evidencia_caminho TEXT NOT NULL,
  evidencia_inicio_linha INTEGER NOT NULL CHECK (evidencia_inicio_linha > 0),
  evidencia_inicio_coluna INTEGER NOT NULL CHECK (evidencia_inicio_coluna > 0),
  evidencia_fim_linha INTEGER NOT NULL CHECK (evidencia_fim_linha > 0),
  evidencia_fim_coluna INTEGER NOT NULL CHECK (evidencia_fim_coluna > 0),
  CONSTRAINT relacoes_importacao_indice_evidencia_ordenada CHECK (
    evidencia_fim_linha > evidencia_inicio_linha
    OR (
      evidencia_fim_linha = evidencia_inicio_linha
      AND evidencia_fim_coluna >= evidencia_inicio_coluna
    )
  ),
  CONSTRAINT relacoes_importacao_indice_id_fato_unico UNIQUE (snapshot_id, id_fato),
  CONSTRAINT relacoes_importacao_indice_tipo_valido CHECK (tipo = 'importa'),
  CONSTRAINT relacoes_importacao_indice_destino_valido CHECK (
    (
      destino_tipo = 'interno'
      AND destino_caminho IS NOT NULL
      AND destino_especificador IS NULL
      AND destino_expressao IS NULL
    )
    OR (
      destino_tipo = 'externo'
      AND destino_caminho IS NULL
      AND destino_especificador IS NOT NULL
      AND destino_expressao IS NULL
    )
    OR (
      destino_tipo = 'nao-resolvido'
      AND destino_caminho IS NULL
      AND destino_especificador IS NOT NULL
    )
  ),
  CONSTRAINT relacoes_importacao_indice_arquivo_fk
    FOREIGN KEY (snapshot_id, arquivo_origem_id)
    REFERENCES arquivos_indice(snapshot_id, id_fato)
    ON DELETE CASCADE,
  CONSTRAINT relacoes_importacao_indice_destino_interno_fk
    FOREIGN KEY (snapshot_id, destino_caminho)
    REFERENCES arquivos_indice(snapshot_id, caminho)
    ON DELETE CASCADE,
  CONSTRAINT relacoes_importacao_indice_evidencia_fk
    FOREIGN KEY (snapshot_id, evidencia_caminho)
    REFERENCES arquivos_indice(snapshot_id, caminho)
    ON DELETE CASCADE
);

CREATE TABLE diagnosticos_indice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL,
  id_fato TEXT NOT NULL,
  codigo TEXT NOT NULL,
  categoria TEXT NOT NULL,
  arquivo_origem_id TEXT,
  evidencia_caminho TEXT NOT NULL,
  evidencia_inicio_linha INTEGER NOT NULL CHECK (evidencia_inicio_linha > 0),
  evidencia_inicio_coluna INTEGER NOT NULL CHECK (evidencia_inicio_coluna > 0),
  evidencia_fim_linha INTEGER NOT NULL CHECK (evidencia_fim_linha > 0),
  evidencia_fim_coluna INTEGER NOT NULL CHECK (evidencia_fim_coluna > 0),
  CONSTRAINT diagnosticos_indice_evidencia_ordenada CHECK (
    evidencia_fim_linha > evidencia_inicio_linha
    OR (
      evidencia_fim_linha = evidencia_inicio_linha
      AND evidencia_fim_coluna >= evidencia_inicio_coluna
    )
  ),
  CONSTRAINT diagnosticos_indice_id_fato_unico UNIQUE (snapshot_id, id_fato),
  CONSTRAINT diagnosticos_indice_codigo_valido CHECK (
    codigo IN ('ERRO_SINTATICO', 'COMMONJS_NAO_SUPORTADO', 'IMPORT_DINAMICO_NAO_RESOLVIDO')
  ),
  CONSTRAINT diagnosticos_indice_categoria_valida CHECK (categoria IN ('sintaxe', 'limitacao')),
  CONSTRAINT diagnosticos_indice_arquivo_origem_coerente CHECK (
    arquivo_origem_id IS NULL OR arquivo_origem_id <> ''
  ),
  CONSTRAINT diagnosticos_indice_arquivo_fk
    FOREIGN KEY (snapshot_id, arquivo_origem_id)
    REFERENCES arquivos_indice(snapshot_id, id_fato)
    ON DELETE CASCADE,
  CONSTRAINT diagnosticos_indice_evidencia_fk
    FOREIGN KEY (snapshot_id, evidencia_caminho)
    REFERENCES arquivos_indice(snapshot_id, caminho)
    ON DELETE CASCADE
);
