CREATE TABLE repositorios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  proprietario TEXT NOT NULL,
  nome TEXT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repositorio_id BIGINT NOT NULL REFERENCES repositorios(id) ON DELETE CASCADE,
  commit_sha CHAR(40) NOT NULL CHECK (commit_sha ~ '^[0-9a-fA-F]{40}$'),
  referencia TEXT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT snapshots_repositorio_commit_unico UNIQUE (repositorio_id, commit_sha)
);
