CREATE TABLE solicitacoes_analise (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id UUID NOT NULL UNIQUE,
  operacao TEXT NOT NULL,
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
  url_normalizada TEXT,
  tentativa_esperada INTEGER,
  tentativa_resultante INTEGER NOT NULL CHECK (tentativa_resultante >= 1),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT solicitacoes_analise_operacao_valida CHECK (operacao IN ('criacao', 'retry')),
  CONSTRAINT solicitacoes_analise_entrada_coerente CHECK (
    (operacao = 'criacao' AND url_normalizada IS NOT NULL AND tentativa_esperada IS NULL)
    OR
    (operacao = 'retry' AND url_normalizada IS NULL AND tentativa_esperada IS NOT NULL)
  )
);

CREATE INDEX solicitacoes_analise_snapshot_idx ON solicitacoes_analise (snapshot_id);
